services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-frontend
    container_name: app-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    working_dir: /usr/src/app
    command: yarn start