export const messageData = [
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
  {
    pNo: "#120",
    messageContent: "Lorem ipsum dolor sit amet, consectetur adipi...",
    postedBy: "Courtney Henry",
    views: "20000",
    pay: "$0.56",
    email: "CourtneyHenry@gmail.com",
    timePosted: "April 28, 2024",
    action: "Edit",
  },
];
export const userData = [
  {
    pNo: "#120",
    userName: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    totalMessages: "200",
    totalViews: "20000",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipi...",
  },
  {
    pNo: "#120",
    userName: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    totalMessages: "200",
    totalViews: "20000",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipi...",
  },
  {
    pNo: "#120",
    userName: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    totalMessages: "200",
    totalViews: "20000",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipi...",
  },
];
export const contactData = [
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
  {
    pNo: "#120",
    name: "Courtney Henry",
    email: "CourtneyHenry@gmail.com",
    subject: "Lorem ipsum dolor sit amet, consectetur adipi...",
    message: "Lorem ipsum dolor sit amet, consectetur adipi...",
    action: "Edit",
  },
];
